### ISSUE TITLE
Squashed Up Log-In Page

### ISSUE THREAD

**Issue by LuckyGold7** [CodeAsherPlayz/Full-Login-Page#12]
**Describe the bug**

The log-in page body is squashed up and the inputs are incorrectly placed.

**To Reproduce**

1. Open Version 1.0 Beta 
2. See error

**Expected behavior**

The body in the log-in page should be wide and not squashed.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.1
 - Browser Google
 - Version 1.0-Beta

**Additional context**

None.

**Comment by CodeAsherPlayz** [comment]
We are currently reviewing this issue. Please give us some time to fix this as we are currently developing v2.0-beta. We will be squashing the bug after v2.0-beta has been completed.

**Comment by CodeAsherPlayz** [comment]
We have finished looking into the problem. The bug rollout will be in v1.0. Thanks for finding this bug!
