### ISSUE TITLE
When will version 1.0 be coming out?

### ISSUE THREAD

**Issue by LuckyGold7** [CodeAsherPlayz/Full-Login-Page#13]
**Is your feature request related to a problem? Please describe.**

I always get irritated when I am using the beta version of v1.0. I addressed this problem already. Issue #12 is one example.

**Describe the solution you'd like**

Please fix the big so that you can release v1.0.

**Comment by CodeAsherPlayz** [comment]
We have already addressed problem #12. It will be rolling out when v1.0. is released. However, we need to finalise a few things in v2.0-beta first before we work on #12. Thank you for your understanding.

**Comment by CodeAsherPlayz** [comment]
Hello @LuckyGold7.

We would like to inform you that we will be rolling out the update earlier. Please check #22 and milestones. Thanks!
