### ISSUE TITLE
More Issue Templates

### ISSUE THREAD

**Issue by LuckyGold7** [CodeAsherPlayz/Full-Login-Page#31]
**Is your feature request related to a problem? Please describe.**

Need more Issue Templates 

**Describe the solution you'd like**

Add more Issue Templates :D

**Describe alternatives you've considered**

None.

**Additional context**

Nil.

**Comment by CodeAsherPlayz** [comment]
@LuckyGold7 please approve the pull request if it meets your demands :D Thanks!

**Comment by LuckyGold7** [comment]
Okay tks
