### ISSUE TITLE
When is Version 0.3 coming out?

### ISSUE THREAD

**Issue by LuckyGold7** [CodeAsherPlayz/Full-Login-Page#4]
**Is your feature request related to a problem? Please describe.**

No. I’m just wondering when v0.3. is coming out as I want to actually have a way to log in with a correct username and password.

**Describe the solution you'd like**

You can add JavaScript or Python into the new update.

**Describe alternatives you've considered**

Use the variables in Python.

**Additional context**

None.

**Comment by CodeAsherPlayz** [comment]
This question is invalid. As already mentioned, this question has been addressed in the Wikipedia sidebar and the Version pre-release. We will look into your suggestions and thank you for stopping by our repository.
