### ISSUE TITLE
File Name Error in GitHub description

### ISSUE THREAD

**Issue by LuckyGold7** [CodeAsherPlayz/Full-Login-Page#5]
There seems that the file name stated in most version can’t be found. @CodeAsherPlayz

**Comment by CodeAsherPlayz** [comment]
I see... I will address this in v0.2.1 < not including v0.3 and v0.4 as I already assigned those advisory.

**Comment by LuckyGold7** [comment]
Please reopen this issue.

**Comment by LuckyGold7** [comment]
I found out these Version 1.0 did not follow the standards met in Version 0.2.1.

**Comment by CodeAsherPlayz** [comment]
I have just taken a look at it and we released that there was a copy-paste error again. We will be correcting this soon when that Version will be released. Please message on this thread to remind us on Release Day just in case we forgot. Thanks!

**Comment by CodeAsherPlayz** [comment]
I have changed the description. There shouldn't be anything else. Thanks!
