### ISSUE TITLE
The HTML file doesn’t have the CSS Settings

### ISSUE THREAD

**Issue by LuckyGold7** [CodeAsherPlayz/Full-Login-Page#6]
**Describe the bug**

When I opened the HTML document, I don’t see any CSS settings in the document.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the HTML file
2. Click on the HTML file 
3. See that no CSS Styling can be seen in the document

**Expected behaviour**

The document should have had CSS Styling in it.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.1
 - Browser: Google
 - Version 0.2

**Additional context**

I hope this gets fixed soon.

**Comment by CodeAsherPlayz** [comment]
I will look into this and reply to you as soon as possible.

**Comment by CodeAsherPlayz** [comment]
I see.. I have spotted the error. This is because I used the external styling option and forgot to change the name of the file. Thank you for contributing. I will roll out v0.2.1 soon to address this issue. This issue will be left open as an advisory to anyone that might be using v0.2 or earlier.

**Comment by CodeAsherPlayz** [comment]
**Advisory** 

This issue (#6) will be resolved under the v0.2.1 update. Please refrain from using versions earlier than v0.2.1.
