### ISSUE TITLE
Logo not appearing 

### ISSUE THREAD

**Issue by LuckyGold7** [CodeAsherPlayz/Full-Login-Page#7]
**Describe the bug**

The logo doesn’t appear.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open the file in a browser
2. See that there is no logo

**Expected behavior**

The logo should be there.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.1
 - Browser Google
 - Version 0.2.1

**Comment by CodeAsherPlayz** [comment]
Thank you for using the software.

We have looked through the issue and reproduced the problem. It seems that the directory of the file is incorrect. We will be patching this in Version 1.0 

Thank you for finding the issue.
